 name: gitartwork from a contribution graph
 on: 
   push:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: Thorfinn05/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: Thorfinn05
            # Text on contribution graph 
            text: RUDRANIL
       - uses: Thorfinn05/simple-push-action@v1
